openapi: 3.0.3
info:
  version: 1.0.0
  title: "SIAAS Local API"
  description: "Local API running in the SIAAS Agent"

paths:
  /:
    get:
      tags:
        - "index"
      summary: "Local API information"
      description: "Shows details about the local API running in the agent"
      responses:
        '200':
          description: "Success"
  /siaas-agent:
    get:
      tags:
        - "siaas-agent"
      summary: "Gets agent data"
      description: "Shows module and configuration data from the local DBs"
      parameters:
        - name: module
          description: "Filters specific modules (accepts multiple values, comma-separated)"
          in: query
          explode: false
          required: false
          allowReserved: true
          schema:
            type: array
            items:
              type: string
              enum: ["platform","neighborhood","portscanner","config","*"]
            default: ["*"]
          #example: ["neighborhood","portscanner"] # comment to avoid: https://github.com/swagger-api/swagger-ui/issues/5776
      responses:
        '200':
          description: "Success"
        '500':
          description: "Bad input or server error"
